version: "3.7"

secrets:
  zap2xml_user:
    file: ./zap2xml_user.secret
  zap2xml_passwd:
    file: ./zap2xml_passwd.secret

services:
  database:
    image: delnaught/mythtv-database:main-32-focal
    ports:
      - 3306:3306
    volumes:
      - /media/data/mysql:/var/lib/mysql
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    restart: "unless-stopped"
  backend:
    image: delnaught/mythtv-backend:main-32-focal
    # entrypoint: ["sh", "-c", "while true; do date; sleep 10; done"]
    entrypoint: ["sh", "-c", "ZAP2XML_USER=$$(cat /run/secrets/zap2xml_user) ZAP2XML_PASSWD=$$(cat /run/secrets/zap2xml_passwd) mythbackend --noupnp"]
    hostname: mrx
    user: 105:107
    network_mode: "host"
    volumes:
      - /media/data/mythtv/content:/var/lib/mythtv
      - /media/data/mythtv/config.xml:/etc/mythtv/config.xml:ro
    environment:
      XMLTV_FILE: /var/lib/mythtv/zap2it/xmltv.xml
      EPG_DAYS: 10
      ICON_DIR: /var/lib/mythtv/.mythtv/channels
      SOURCE_ID: 1
    secrets:
      - zap2xml_user
      - zap2xml_passwd
    restart: "unless-stopped"
  
