version: "3.7"

secrets:
  ZAP2XML_USER:
    file: ./zap2xml_user.secret
  ZAP2XML_PASSWD:
    file: ./zap2xml_passwd.secret
  MARIADB_ROOT_PASSWORD:
    file: ./mariadb_root_password.secret

services:
  database:
    image: delnaught/mythtv-database:main-32-focal
    ports:
      - 3306:3306
    volumes:
      - /media/data/mysql:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
    restart: "unless-stopped"
  backend:
    image: delnaught/mythtv-backend:main-32-focal
    # entrypoint: ["sh", "-c", "while true; do date; sleep 10; done"]
    entrypoint: ["mythbackend", "--noupnp"]
    hostname: mrx
    user: 105:107
    network_mode: "host"
    volumes:
      - /media/data/mythtv/content:/var/lib/mythtv
      - /media/data/mythtv/config.xml:/etc/mythtv/config.xml:ro
    environment:
      XMLTV_FILE: /var/lib/mythtv/zap2it/xmltv.xml
      EPG_DAYS: 10
      ICON_DIR: /var/lib/mythtv/.mythtv/channels
      SOURCE_ID: 1
    secrets:
      - ZAP2XML_USER
      - ZAP2XML_PASSWD
    restart: "unless-stopped"
  
