---

name: build-and-publish-database

on:
  workflow_call:
    inputs:
      source-ref:
        description: 'source ppa version for mythtv'
        required: true
        type: string
      source-date:
        description: 'date of source ppa version'
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: mariadb.dockerfile
          build-args: |
            BUILDER_IMAGE=ubuntu:focal
            RUNTIME_IMAGE=mariadb:10.3-focal
            MYTHTV_VERSION=${{ inputs.source-ref }}
          labels: |
            mythtv.source_package_version=${{ inputs.source-ref }}
          tags: |
            delnaught/mythtv-database:32-focal-${{ inputs.source-date }}
