---

name: 'Mythbuntu PPA Build Records'
description: 'fetch Mythbuntu build records for a given ppa, architecture, and os release'

inputs:
  images-names:
    description: 'JSON array of images to be built'
    required: true
  ppa-names:
    description: 'JSON array of mythbuntu PPA names'
    required: true
  record-count:
    description: 'build records per PPA fetched prior to filtering'
    required: false
    default: 40
  build-os:
    description: 'OS version of interest'
    required: false
    default: '20.04'
  build-arch:
    description: 'arhitecture of interest'
    required: false
    default: 'amd64'

outputs:
  build-matrix:
    description: 'package information in a json array'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.image-names }}
    - ${{ inputs.ppa-names }}
    - ${{ inputs.record-count }}
    - ${{ inputs.build-os }}
    - ${{ inputs.build-arch }}
