---

name: deliver-on-skew

on:
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/deliver-on-skew.yml
      - .github/workflows/fetch-image-metadata.yml
      - .github/workflows/fetch-mythbuntu-ppa.yml
      - .github/workflows/get-version-skew.yml

jobs:
  fetch-backend-meta:
    uses: delnaught/mythtv-containers/.github/workflows/fetch-image-metadata.yml@query-dockerhub
    with:
      image: delnaught/mythtv-backend
      tag: 32
  fetch-backend-ppa:
    uses: delnaught/mythtv-containers/.github/workflows/fetch-mythbuntu-ppa.yml@query-dockerhub
    with:
      ppa: 32
      depth: 50
  get-image-skew:
    needs:
      - fetch-backend-meta
      - fetch-backend-ppa
    uses: delnaught/mythtv-containers/.github/workflows/get-version-skew.yml@query-dockerhub
    with:
      ppa: ${{ needs.fetch-backend-ppa.outputs.versions }}
      ref: ${{ needs.fetch-backend-meta.outputs.metadata }}
