---

name: deliver-on-skew

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/deliver-on-skew.yml
      - .github/workflows/fetch-image-metadata.yml

jobs:
  fetch-image-meta:
    uses: delnaught/mythtv-containers/.github/workflows/fetch-image-metadata.yml@query-dockerhub
    with:
      image: delnaught/mythtv-backend
      tag: 32
  get-image-skew:
    runs-on: ubuntu-latest
    needs: fetch-image-meta
    steps:
      - run: |
          image_version=$(echo "${{ needs.fetch-image-meta.outputs.metadata }}" | jq -r '.config.Labels."mythtv.source_package_version"')
          echo $image_version

