---

name: deliver-on-skew

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/deliver-on-skew.yml
      - .github/workflows/fetch-image-metadata.yml

jobs:
  fetch-image-meta:
    uses: delnaught/mythtv-containers/.github/workflows/fetch-image-metadata.yml@${{ env.GITHUB_REF_NAME }}
    with:
      image: delnaught/mythtv-backend
      tag: 32
  get-image-skew:
    needs: fetch-image-meta
    steps:
      - run: echo ${{ needs.fetch-image-meta.outputs.metadata }}

