---

name: deliver-on-skew

on:
  push:
    paths:
      - '.github/workflows/*'
      - '**.dockerfile'

jobs:
  fetch-mythbuntu-ppa:
    uses: delnaught/mythtv-containers/.github/workflows/fetch-mythbuntu-ppa.yml@query-dockerhub
    with:
      mythbuntu-release: 32
      os-release: 20.04
      record-count: 30
  fetch-backend-meta:
    uses: delnaught/mythtv-containers/.github/workflows/fetch-image-metadata.yml@query-dockerhub
    with:
      image: delnaught/mythtv-backend
      tag: 32
  get-backend-skew:
    needs:
      - fetch-mythbuntu-ppa
      - fetch-backend-meta
    uses: delnaught/mythtv-containers/.github/workflows/get-version-skew.yml@query-dockerhub
    with:
      ppa: ${{ needs.fetch-mythbuntu-ppa.outputs.versions }}
      meta: ${{ needs.fetch-backend-meta.outputs.metadata }}
      image: delnaught/mythtv-backend
  deliver-backend:
    runs-on: ubuntu-latest
    needs:
      - get-backend-skew
    if: ${{ 0 < needs.get-backend-skew.outputs.length }}
    strategy:
      matrix:
        include: ${{ fromJson(needs.get-backend-skew.outputs.matrix) }}
    steps:
      - env:
          SOURCE: ${{ matrix.source }}
          TAGS: ${{ matrix.tags }}
        run: |
          echo "::debug source input ${{ matrix.source }}"
          echo "::debug tags input ${{ matrix.tags }}"
          echo "::debug source env $SOURCE"
          echo "::debug tags env $TAGS"
          echo "env $SOURCE => $TAGS}"
          echo "input ${{ matrix.source }} => ${{ matrix.tags }}"
      # - uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     file: mythtv.dockerfile
      #     build-args: |
      #       FROM_IMAGE: ubuntu:focal
      #       MYTHTV_VERSION=${{ matrix.version }}
      #     labels: |
      #       mythtv.source_package_version=${{ matrix.version }}
      #     tags: |
      #       delnaught/mythtv-backend:${{ steps.generate-tag.outputs.tag }}
