---

name: deliver-on-skew

on:
  push:
    paths:
      - '.github/workflows/*'
      - '**.dockerfile'

jobs:
  fetch-mythbuntu-ppa:
    uses: delnaught/mythtv-containers/.github/workflows/fetch-mythbuntu-ppa.yml@query-dockerhub
    with:
      mythbuntu-release: 32
      os-release: 20.04
      record-count: 30
  fetch-backend-meta:
    uses: delnaught/mythtv-containers/.github/workflows/fetch-image-metadata.yml@query-dockerhub
    with:
      image: delnaught/mythtv-backend
      tag: 32
  get-backend-skew:
    needs:
      - fetch-mythbuntu-ppa
      - fetch-backend-meta
    uses: delnaught/mythtv-containers/.github/workflows/get-version-skew.yml@query-dockerhub
    with:
      ppa: ${{ needs.fetch-mythbuntu-ppa.outputs.versions }}
      meta: ${{ needs.fetch-backend-meta.outputs.metadata }}
      image: delnaught/mythtv-backend
  deliver-backend:
    runs-on: ubuntu-latest
    needs:
      - get-backend-skew
    if: ${{ 0 < needs.get-backend-skew.outputs.length }}
    strategy:
      matrix:
        build: ${{ fromJson(needs.get-backend-skew.outputs.builds) }}
    steps:
      - id: generate-tags
        run: |
          image="delnaught/mythtv-backend"
          tags=$(echo ${{ matrix.build }} | jq --arg image $image -r '.
          | { "source" : .
          , "tags" : . | match("^[0-9]+:([0-9]+)\\.([0-9]+)[~\\+][a-z]+\\.([0-9]+)\\.").captures | (
          $image + ":" + .[0].string + "." + .[1].string + "." + .[2].string + "," +
          $image + ":" + .[0].string + "." + .[1].string + "," +
          $image + ":" + .[0].string)
          }')
          echo "::debug ${{ matrix.build }} => $tags"
          echo "::set-output name=tags::${tags}"
      - id: build-push-stub
        run: |
          echo "::debug source: ${{ matrix.build}} tags: ${{ steps.generate-tags.outputs.tags }}"
          echo "source: ${{ matrix.build}} tags: ${{ steps.generate-tags.outputs.tags }}"
      # - uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     file: mythtv.dockerfile
      #     build-args: |
      #       FROM_IMAGE: ubuntu:focal
      #       MYTHTV_VERSION=${{ matrix.source }}
      #     labels: |
      #       mythtv.source_package_version=${{ matrix.source }}
      #     tags: ${{ matrix.tags }}
