---

name: deliver-on-skew

on:
  push:
    paths:
      - '.github/workflows/*'
      - '**.dockerfile'

jobs:
  fetch-mythbuntu-ppa:
    uses: delnaught/mythtv-containers/.github/workflows/fetch-mythbuntu-ppa.yml@query-dockerhub
    with:
      ppa: 32
      depth: 50
  fetch-backend-meta:
    uses: delnaught/mythtv-containers/.github/workflows/fetch-image-metadata.yml@query-dockerhub
    with:
      image: delnaught/mythtv-backend
      tag: 32
  get-backend-skew:
    needs:
      - fetch-mythbuntu-ppa
      - fetch-backend-meta
    uses: delnaught/mythtv-containers/.github/workflows/get-version-skew.yml@query-dockerhub
    with:
      ppa: ${{ needs.fetch-mythbuntu-ppa.outputs.versions }}
      meta: ${{ needs.fetch-backend-meta.outputs.metadata }}
