---

name: Skew and Deliver

on: push

jobs:
  deliver-skew:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ppa: ["32"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: query-ppa
        uses: .github/actions/ppa-build-records-action
        with:
          ppa-name: ${{ matrix.ppa }}
      - id: dump-versions
        run: |
          echo "::debug versions => ${{ steps.query-ppa.outputs.package-versions }}"
          echo "::debug latest => ${{ steps.query-ppa.outputs.latest-version }}"
      
    
