---

name: Skew and Deliver

on: push

jobs:
  query-ppa:
    runs-on: ubuntu-latest
    outputs:
      build-records: ${{ steps.query.outputs.build-records }}
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: query
        uses: ./.github/actions/ppa-build-records-action
        with:
          ppa-name: "32"
          
  build-images:
    runs-on: ubuntu-latest
    needs:
      - query-ppa
    strategy:
      matrix:
        include: ${{ fromJson(needs.query-ppa.outputs.build-records) }}
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: build-tag-set
        run: |
          tag_commit=${{matrix.commit}}
          tag_full=${{matrix.major}}.${{matrix.minor}}.${{matrix.date}}-${{matrix.commit}}
          tag_minor=${tag_full%.*}
          tag_major=${tag_minor%.*}
          if [[ "0" == ${{ matrix.index }} ]]; then
          echo "::set-output name=tags::${tag_commit},${tag_full},${tag_minor},${tag_major},latest"
          else
          echo "::set-output name=tags::${tag_commit},${tag_full}"
          fi
      - id: query-backend-image
        uses: ./.github/actions/dockerhub-image-action
        with:
          image-name: delnaught/mythtv-backend
          image-tag: ${{matrix.commit}}
      - id: dump-dockerhub-code
        run: |
          echo "::debug ${{ steps.query-backend-image.outputs.http-code }}"
      - id: conditional-build
        if: ${{ "404" == steps.query-backend-image.outputs.http-code }}
        run: |
          echo "::debug reached!"
