---

name: Skew and Deliver

on: push

jobs:
  query-ppa:
    runs-on: ubuntu-latest
    outputs:
      package-versions: ${{ steps.query.outputs.package-versions }}
      latest-version: ${{ steps.query.outputs.latest-version }}
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: query
        uses: ./.github/actions/ppa-build-records-action
        with:
          ppa-name: "32"
      - id: dump-versions
        run: |
          echo "::debug versions => ${{ steps.query.outputs.package-versions }}"
          echo "::debug latest => ${{ steps.query.outputs.latest-version }}"

          
  build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source-version: ${{ jobs.query-ppa.outputs.package-versions }}
    steps:
      - id: dump-versions
        run: |
          echo "::debug versions => ${{ jobs.query-ppa.outputs.package-versions }}"
          echo "::debug latest => ${{ jobs.query-ppa.outputs.latest-version }}"
          echo "::debug source => ${{ matrix.source-version }}"
