---

name: Skew and Deliver

on: push

jobs:
  query-ppa:
    runs-on: ubuntu-latest
    outputs:
      build-records: ${{ steps.query.outputs.build-records }}
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: query
        uses: ./.github/actions/ppa-build-records-action
        with:
          ppa-name: "32"
      - id: dump-versions
        run: |
          echo "::debug versions => ${{ steps.query.outputs.build-records }}"

          
  build-images:
    runs-on: ubuntu-latest
    needs:
      - query-ppa
    strategy:
      matrix:
        include: ${{ fromJson(needs.query-ppa.outputs.build-records) }}
    steps:
      - id: dump-versions
        run: |
          echo "::debug index => ${{ matrix.index }}"
          echo "::debug index => ${{ matrix.version }}"
          echo "::debug index => ${{ matrix.date }}"
